//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentUpload
    {
        public int AssignmentUploadId { get; set; }
        public System.DateTime AssignmentUploadSubmittedOn { get; set; }
        public string AssignmentUploadGrade { get; set; }
        public double AssignmentUploadMarks { get; set; }
        public bool AssignmentUploadIsAfterDeadline { get; set; }
        public String AssignmentUploadLecturerComment { get; set; }
        public int AssignmentId { get; set; }
        public int StudentId { get; set; }
        public List<Attachment> Attachments { get; set; }

        public virtual Assignment Assignment { get; set; }
        public virtual Student Student { get; set; }
    }
}
