//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.AssignmentUploads = new HashSet<AssignmentUpload>();
        }
    
        public int AssignmentId { get; set; }
        public string AssignmentName { get; set; }
        public string AssignmentDescription { get; set; }
        public System.DateTime AssignmentIssuedOn { get; set; }
        public System.DateTime AssignmentMarksReleaseOn { get; set; }
        public System.DateTime AssignmentDeadline { get; set; }
        public double AssignmentMaxFileSize { get; set; }
        public int SubjectId { get; set; }
        public List<Attachment> Attachments { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentUpload> AssignmentUploads { get; set; }
    }
}
