//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentId { get; set; }
        public string AttachmentName { get; set; }
        public double AttachmentFileSize { get; set; }
        public string AttachmentUrl { get; set; }
        public string AttachmentReferenceType { get; set; }
        public int AttachmentReferenceId { get; set; }
    }
}
