//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureNote
    {
        public int LectureNoteid { get; set; }
        public string LectureNoteName { get; set; }
        public string LectureNoteDescription { get; set; }
        public System.DateTime LectureNoteSubmittedOn { get; set; }
        public System.DateTime LectureNoteDate { get; set; }
        public int SubjectId { get; set; }
        public List<Attachment> Attachments { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
