//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterResult
    {
        public int SemesterResultId { get; set; }
        public double SemesterResultMarks { get; set; }
        public string SemesterResultGrade { get; set; }
        public int SemesterId { get; set; }
        public int StudentId { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
