//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyMaterial
    {
        public int StudyMaterialId { get; set; }
        public string StudyMaterialName { get; set; }
        public string StudyMaterialDescription { get; set; }
        public System.DateTime StudyMaterialSubmittedOn { get; set; }
        public int SubjectId { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
