//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubject
    {
        public int StudentSubjectId { get; set; }
        public double StudentSubjectMarks { get; set; }
        public string StudentSubjectGrade { get; set; }
        public int SubjectId { get; set; }
        public int StudentId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
